CREATE SEQUENCE IF NOT EXISTS ingresojuego_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;



-- Secuencia para módulos
CREATE SEQUENCE IF NOT EXISTS modulo_seq
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9900
  CACHE 1
  NO CYCLE;


-- Secuencia para teorias
CREATE SEQUENCE IF NOT EXISTS teoria_seq
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9900
  CACHE 1
  NO CYCLE;


-- Secuencia para actividades
CREATE SEQUENCE IF NOT EXISTS actividad_seq
  START WITH 1
  INCREMENT BY 1
  MAXVALUE 9900
  CACHE 1
  NO CYCLE;


-- Secuencia para grupos
CREATE SEQUENCE IF NOT EXISTS grupo_seq
  START WITH 1000
  INCREMENT BY 1
  MAXVALUE 99000
  CACHE 1
  NO CYCLE;


-- Secuencia para refuerzos
CREATE SEQUENCE IF NOT EXISTS refuerzo_seq
  START WITH 1
  INCREMENT BY 1
  NO MAXVALUE
  CACHE 1
  NO CYCLE;


-- Secuencia para juegos
CREATE SEQUENCE IF NOT EXISTS juego_seq
  START WITH 100
  INCREMENT BY 1
  NO MAXVALUE
  CACHE 1
  NO CYCLE;


-- Secuencia para componentes
CREATE SEQUENCE IF NOT EXISTS componente_seq
  START WITH 100
  INCREMENT BY 1
  NO MAXVALUE
  CACHE 1
  NO CYCLE;
